### ISSUE TITLE
TookitCleaner: Node 18 Lambdas do not have aws-sdk@2

### ISSUE THREAD

**Issue by joeflateau** [jogold/cloudstructs#211]
I attempted to deploy `ToolkitCleaner` as a brand new stack but the lambdas fail to execute. Seems that they attempt to require `aws-sdk` which is assumed to be available in the lambda environment but that's not the case in node 18 lambdas which only have aws-sdk@3

Runtime.ImportModuleError in step: GetStackNames

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
    "    at async start (file:///var/runtime/index.mjs:1200:23)",
    "    at async file:///var/runtime/index.mjs:1206:1"
  ]
}
```

**Comment by jogold** [comment]
Thanks for reporting, I reverted the change in the meantime.

**Comment by joeflateau** [comment]
thank you!
